# XGBoost Model Hyperparameters
learning:
  model_params:
    xgboost:
      module_path: xgboost
      model_type: XGBClassifier
      train_params:
        booster: gbtree
        learning_rate: 0.05
        n_estimators: 100
        max_depth: 5
        min_child_weight: 3
        gamma: 0
        subsample: 1.0
        colsample_bytree: 0.8
        objective: binary:logistic
        random_state: 42
        eval_metric: aucpr
        reg_alpha: 0.01
        reg_lambda: 10
      fit_params:
        verbose: False
